<?php

use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Url;

/**
 * Implements hook_social_user_account_header_items().
 *
 * Adds an indicator to the user account menu.
 */
function im_commons_social_user_account_header_items_alter(array &$menu_links, array $context) {
  // We require a logged in user for this indicator.
  if (empty($context['user']) || !$context['user']->isAuthenticated()) {
    return;
  }

  // If the account_box link was removed we have nothing to do.
  if (!isset($menu_links['account_box'])) {
    return;
  }

  $uid = $context['user']->id();
  \Drupal::logger('im_commons')->info('im_commons_social_user_account_header_items ' . $uid);

  // Define the "My Orders" link.
  $my_orders_link = [
    '#type' => 'link',
    '#title' => new TranslatableMarkup('My orders'),
    '#attributes' => [
      'title' => new TranslatableMarkup('View my orders'),
    ],
    '#url' => Url::fromUserInput("/user/" . $uid . "/orders"),
    '#weight' => 700,
  ];

  // Add the "My Orders" link to the account_box menu.
  $menu_links['account_box']['my_orders'] = $my_orders_link;
}