name: Config Modify
description: Allows automatic modification of existing config during config installation.
type: module
core_version_requirement: ^9 || ^10
dependencies:
  - drupal:config
  # This is needed for the CUD system.
  - update_helper:update_helper

# Information added by Drupal.org packaging script on 2023-04-13
version: '1.0.0-rc1'
project: 'config_modify'
datestamp: 1681376829
