<?php

/**
 * @file
 * Code for the Commerce Webform Order Demo module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function commerce_webform_order_demo_help($route_name, RouteMatchInterface $route_match) {
  /** @var \Drupal\webform\WebformEntityStorageInterface $webform_storage */
  $webform_storage = \Drupal::entityTypeManager()->getStorage('webform');

  $webform_ids = $webform_storage->getQuery()
    ->accessCheck(FALSE)
    ->condition('id', 'cwo_demo_', 'STARTS_WITH')
    ->execute();

  if (!empty($webform_ids)) {
    $webforms = $webform_storage->loadMultiple($webform_ids);

    $output = '';
    $output .= '<h3>' . t('Commerce Webform Order Demo') . '</h3>';
    $output .= '<p>' . t('The following sample forms are available:') . '</p>';
    $output .= '<dl>';
    foreach ($webforms as $webform) {
      $output .= '<dt>' . t('<a href=":page_submit_path">@webform</a>', [
        ':page_submit_path' => Url::fromUserInput($webform->getSetting('page_submit_path'))->toString(),
        '@webform' => $webform->label(),
      ]) . '</dt>';
      $output .= '<dd>' . $webform->getDescription() . '</dd>';
    }
    $output .= '</dl>';

    return $output;
  }
}
